Remove failure

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -26,8 +26,8 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - name: Fail the action
-        run: exit 1
+      # - name: Fail the action
+      #   run: exit 1
 
       - name: Run a one-line script
         run: echo PUBLISH TO NPM
