add more stuff

diff --git a/.github/workflows/publish-all-in-one.yml b/.github/workflows/publish-all-in-one.yml
--- a/.github/workflows/publish-all-in-one.yml
+++ b/.github/workflows/publish-all-in-one.yml
@@ -9,17 +9,7 @@ on:
         default: true
 
 jobs:
-  build_release:
-    name: Build the release
-    runs-on: ubuntu-22.04
-
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Run a one-line script
-        run: echo BUILD THE RELEASE
   prepare_npm:
-    needs: [build_release]
     name: Prepare npm 
     runs-on: ubuntu-22.04
 
@@ -59,8 +49,33 @@ jobs:
 
       - name: Run a one-line script
         run: echo DRY RUN TO NPM
-  github_releases:
-    needs: [dry_run_npm, publish_to_npm] # Ensure that this job only runs if npm succeeds
+  prepare_github_release:
+    needs: [publish_to_npm, dry_run_npm]
+    name: Prepare Github Release 
+    runs-on: ubuntu-22.04
+
+    steps:
+      - uses: actions/checkout@v4
+
+      # - name: Fail the action
+      #   run: exit 1
+
+      - name: Run a one-line script
+        run: echo PUBLISH TO NPM
+  dry_run_github_release:
+    if: inputs.dry_run == true
+    needs: [prepare_github_release]
+    name: Dry Run GitHub Releases
+    runs-on: ubuntu-22.04
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Run a one-line script
+        run: echo DRY RUN GitHub Releases
+  publish_to_github_release:
+    if: inputs.dry_run == false
+    needs: [prepare_github_release]
     name: Publish to GitHub Releases
     runs-on: ubuntu-22.04
 
